package routes

import (
	"github.com/Wei-Shaw/sub2api/internal/handler"
	"github.com/gin-gonic/gin"
)

func registerUpstreamGovernanceRoutes(admin *gin.RouterGroup, h *handler.Handlers) {
	if h.Admin.UpstreamGovernance == nil {
		return
	}
	api := h.Admin.UpstreamGovernance
	g := admin.Group("/upstream-governance")
	g.GET("/import-templates", api.ImportTemplates)
	g.PUT("/import-templates", api.SaveImportTemplates)
	g.GET("/workbench", api.Workbench)
	g.GET("/sites/:id/timeline", api.Timeline)
	g.GET("/model-templates", api.ModelTemplates)
	g.PUT("/model-templates", api.SaveModelTemplates)
	g.GET("/sites", api.List)
	g.POST("/sites", api.Create)
	g.POST("/sites/detect", api.Detect)
	g.PUT("/sites/:id", api.Update)
	g.GET("/sites/:id/login-credentials", api.LoginCredentials)
	g.GET("/sites/:id/auth-status", api.AuthorizationStatus)
	g.GET("/sites/:id/readiness", api.Readiness)
	g.POST("/sites/:id/browser-auth", api.StartBrowserAuthorization)
	g.GET("/sites/:id/browser-auth/:job_id", api.BrowserAuthorization)
	g.POST("/sites/:id/browser-auth/:job_id/actions", api.BrowserAuthorizationAction)
	g.POST("/sites/:id/browser-auth/:job_id/complete", api.CompleteBrowserAuthorization)
	g.DELETE("/sites/:id/browser-auth/:job_id", api.CancelBrowserAuthorization)
	g.PUT("/sites/:id/balance-monitor", api.ConfigureBalanceMonitor)
	g.GET("/sites/:id/balance-health", api.BalanceHealth)
	g.GET("/sites/:id/recharge-plan", api.RechargePlan)
	g.PUT("/sites/:id/recharge-plan", api.ConfigureRechargePlan)
	g.POST("/sites/:id/recharge-plan/evaluate", api.EvaluateRechargePlan)
	g.GET("/sites/:id/automation", api.Automation)
	g.PUT("/sites/:id/automation", api.ConfigureAutomation)
	g.GET("/sites/:id/observation-policy", api.ObservationPolicy)
	g.PUT("/sites/:id/observation-policy", api.ConfigureObservationPolicy)
	g.GET("/sites/:id/pricing-policies", api.PricingPolicies)
	g.PUT("/sites/:id/pricing-policies", api.ConfigurePricingPolicies)
	g.POST("/sites/:id/pricing-policies/:group_id/preview", api.PreviewPricingPolicy)
	g.PUT("/sites/:id/pricing-policies/:group_id", api.ConfigurePricingPolicy)
	g.PUT("/sites/:id/pricing-notifications", api.ConfigurePricingNotifications)
	g.GET("/sites/:id/reconciliation", api.Reconciliation)
	g.POST("/sites/:id/reconcile-preview", api.PreviewReconciliation)
	g.POST("/sites/:id/reconcile-previews/:preview_id/apply", api.ApplyReconciliation)
	g.DELETE("/sites/:id", api.Delete)
	g.POST("/sites/:id/connect", api.Connect)
	g.POST("/sites/:id/sync", api.Sync)
	g.GET("/sites/:id/catalog", api.Catalog)
	g.GET("/sites/:id/bindings", api.Bindings)
	g.GET("/sites/:id/keys", api.Keys)
	g.POST("/sites/:id/keys/audit", api.AuditKeys)
	g.POST("/sites/:id/keys", api.CreateKeys)
	g.POST("/sites/:id/keys/:key_id/reveal", api.RevealKey)
	g.POST("/sites/:id/keys/:key_id/repairs", api.PrepareKeyRepair)
	g.GET("/sites/:id/keys/:key_id/repairs", api.LatestKeyRepair)
	g.POST("/sites/:id/keys/:key_id/repairs/:repair_id/confirm", api.ConfirmKeyRepair)
	g.POST("/sites/:id/keys/:key_id/repairs/:repair_id/abandon", api.AbandonKeyRepair)
	g.POST("/sites/:id/previews", api.Preview)
	g.POST("/sites/:id/previews/:preview_id/apply", api.Apply)
	g.GET("/sites/:id/events", api.Events)
	g.POST("/sites/:id/events/:event_id/ack", api.Acknowledge)
	g.GET("/sites/:id/checks", api.Checks)
	g.POST("/sites/:id/bindings/:binding_id/check", api.Probe)
	g.PUT("/sites/:id/bindings/:binding_id/monitor", api.Monitor)
	g.GET("/sites/:id/model-policies", api.ModelPolicies)
	g.POST("/sites/:id/model-policies", api.SaveModelPolicy)
	g.DELETE("/sites/:id/model-policies/:policy_id", api.DeleteModelPolicy)
	g.POST("/sites/:id/model-batches", api.StartModelBatch)
	g.POST("/sites/:id/model-batches/:batch_id/cancel", api.CancelModelBatch)
	g.GET("/sites/:id/model-runs", api.ModelRuns)
	g.GET("/sites/:id/model-stats", api.ModelStats)
	g.GET("/sites/:id/model-runs/:run_id", api.ModelRun)
	g.PUT("/sites/:id/model-runs/:run_id/review", api.ReviewModelRun)
}
