<template>
  <section aria-labelledby="public-pricing-title" class="border-b border-white/10 bg-[#0a1016] text-slate-100">
    <div class="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20 lg:px-10">
      <div class="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
        <div class="max-w-2xl">
          <h2 id="public-pricing-title" class="mt-2 text-3xl font-semibold tracking-normal text-white sm:text-4xl">{{ t('home.public.pricing.title') }}</h2>
          <p class="mt-3 text-sm leading-6 text-slate-400 sm:text-base">{{ t('home.public.pricing.description') }}</p>
        </div>
        <div v-if="status === 'ready' && rows.length" class="flex items-center gap-2 text-sm text-slate-400"><span class="h-2 w-2 rounded-full bg-emerald-300" aria-hidden="true" />{{ t('home.public.pricing.modelsShown', { shown: filteredRows.length, total: rows.length }) }}</div>
      </div>
      <div class="mt-8 overflow-hidden rounded-lg border border-white/10 bg-[#111a22]">
        <div v-if="status === 'loading'" class="space-y-3 p-5 sm:p-6" aria-busy="true" :aria-label="t('home.public.pricing.loadingAria')"><div v-for="index in 4" :key="index" class="grid animate-pulse gap-3 sm:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)_minmax(0,0.8fr)_minmax(0,0.8fr)]"><span class="h-12 rounded-lg bg-white/[0.06]" /><span class="h-12 rounded-lg bg-white/[0.04]" /><span class="h-12 rounded-lg bg-white/[0.04]" /><span class="h-12 rounded-lg bg-white/[0.04]" /></div></div>
        <div v-else-if="status === 'error'" class="flex flex-col items-center px-5 py-12 text-center" role="alert"><span class="flex h-11 w-11 items-center justify-center rounded-full border border-rose-300/25 bg-rose-300/10 text-rose-200"><Icon name="exclamationTriangle" size="md" aria-hidden="true" /></span><h3 class="mt-4 text-base font-semibold text-white">{{ t('home.public.pricing.errorTitle') }}</h3><p class="mt-2 max-w-md text-sm leading-6 text-slate-400">{{ props.errorMessage || t('home.public.pricing.errorFallback') }}</p><button v-if="props.retryable !== false" type="button" class="mt-5 inline-flex min-h-10 items-center gap-2 rounded-lg border border-white/15 px-4 py-2 text-sm font-semibold text-slate-100" @click="emit('retry')"><Icon name="refresh" size="sm" aria-hidden="true" /> {{ t('home.public.pricing.retry') }}</button></div>
        <div v-else-if="status === 'unavailable'" class="flex flex-col items-center px-5 py-12 text-center"><span class="flex h-11 w-11 items-center justify-center rounded-full border border-cyan-300/25 bg-cyan-300/10 text-cyan-200"><Icon name="ban" size="md" aria-hidden="true" /></span><h3 class="mt-4 text-base font-semibold text-white">{{ t('home.public.pricing.unavailableTitle') }}</h3><p class="mt-2 max-w-md text-sm leading-6 text-slate-400">{{ t('home.public.pricing.unavailableDescription') }}</p></div>
        <div v-else-if="status === 'idle'" class="flex flex-col items-center px-5 py-12 text-center"><span class="flex h-11 w-11 items-center justify-center rounded-full border border-white/15 bg-white/[0.04] text-slate-300"><Icon name="clock" size="md" aria-hidden="true" /></span><h3 class="mt-4 text-base font-semibold text-white">{{ t('home.public.pricing.idleTitle') }}</h3><p class="mt-2 max-w-md text-sm leading-6 text-slate-400">{{ t('home.public.pricing.idleDescription') }}</p></div>
        <div v-else-if="status === 'ready' && !rows.length" class="flex flex-col items-center px-5 py-12 text-center"><span class="flex h-11 w-11 items-center justify-center rounded-full border border-white/15 bg-white/[0.04] text-slate-300"><Icon name="calculator" size="md" aria-hidden="true" /></span><h3 class="mt-4 text-base font-semibold text-white">{{ t('home.public.pricing.emptyTitle') }}</h3><p class="mt-2 max-w-md text-sm leading-6 text-slate-400">{{ t('home.public.pricing.emptyDescription') }}</p></div>
        <template v-else>
          <div class="flex flex-col gap-3 border-b border-white/10 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><label class="relative block min-w-0 sm:w-72"><span class="sr-only">{{ t('home.public.pricing.searchPlaceholder') }}</span><Icon name="search" size="sm" class="pointer-events-none absolute left-3 top-2.5 text-slate-500" aria-hidden="true" /><input v-model="searchQuery" type="search" :placeholder="t('home.public.pricing.searchPlaceholder')" class="h-10 w-full rounded-lg border border-white/10 bg-[#0b1117] pl-9 pr-3 text-sm text-slate-100" /></label><label class="flex items-center gap-2 text-xs text-slate-500"><span>{{ t('home.public.pricing.platform') }}</span><select v-model="platformFilter" class="h-10 rounded-lg border border-white/10 bg-[#0b1117] px-3 text-sm text-slate-200"><option value="all">{{ t('home.public.pricing.allPlatforms') }}</option><option v-for="platform in platforms" :key="platform" :value="platform">{{ platform }}</option></select></label></div>
          <div v-if="!filteredRows.length" class="flex flex-col items-center px-5 py-12 text-center"><span class="flex h-11 w-11 items-center justify-center rounded-full border border-white/15 bg-white/[0.04] text-slate-300"><Icon name="search" size="md" aria-hidden="true" /></span><h3 class="mt-4 text-base font-semibold text-white">{{ t('home.public.pricing.noMatchesTitle') }}</h3><p class="mt-2 max-w-md text-sm leading-6 text-slate-400">{{ t('home.public.pricing.noMatchesDescription') }}</p><button type="button" class="mt-5 inline-flex min-h-10 items-center rounded-lg border border-white/15 px-4 py-2 text-sm font-semibold text-slate-100" @click="resetFilters">{{ t('home.public.pricing.clearFilters') }}</button></div>
          <div v-else class="overflow-x-auto"><table class="min-w-[760px] text-left text-sm"><caption class="sr-only">{{ t('home.public.pricing.caption') }}</caption><thead class="border-b border-white/10 text-xs font-semibold uppercase tracking-wider text-slate-500"><tr><th scope="col" class="px-5 py-3">{{ t('home.public.pricing.table.platform') }}</th><th scope="col" class="px-5 py-3">{{ t('home.public.pricing.table.model') }}</th><th scope="col" class="px-5 py-3">{{ t('home.public.pricing.table.billing') }}</th><th scope="col" class="px-5 py-3">{{ t('home.public.pricing.table.input') }}<br><span class="font-normal normal-case tracking-normal text-slate-600">{{ t('home.public.pricing.table.perToken') }}</span></th><th scope="col" class="px-5 py-3">{{ t('home.public.pricing.table.output') }}<br><span class="font-normal normal-case tracking-normal text-slate-600">{{ t('home.public.pricing.table.perToken') }}</span></th><th scope="col" class="px-5 py-3">{{ t('home.public.pricing.table.cacheRead') }}<br><span class="font-normal normal-case tracking-normal text-slate-600">{{ t('home.public.pricing.table.perToken') }}</span></th><th scope="col" class="px-5 py-3">{{ t('home.public.pricing.table.groups') }}</th></tr></thead><tbody class="divide-y divide-white/10"><tr v-for="row in filteredRows" :key="`${row.platform}-${row.model}`" class="text-slate-300"><td class="whitespace-nowrap px-5 py-4 font-medium capitalize text-white">{{ row.platform }}</td><td class="px-5 py-4 font-mono text-xs text-cyan-100"><div class="whitespace-nowrap">{{ row.model }}</div><span v-if="row.pricingSource === 'official'" class="mt-1 inline-flex rounded border border-amber-300/20 bg-amber-300/10 px-1.5 py-0.5 font-sans text-[10px] font-semibold uppercase tracking-wide text-amber-200">{{ t('home.public.pricing.officialReference') }}</span><span v-else-if="row.pricingSource === 'unavailable'" class="mt-1 inline-flex rounded border border-white/10 bg-white/[0.04] px-1.5 py-0.5 font-sans text-[10px] font-semibold uppercase tracking-wide text-slate-500">{{ t('home.public.pricing.noPricePublished') }}</span></td><td class="whitespace-nowrap px-5 py-4 text-xs uppercase tracking-wide text-slate-400">{{ billingLabel(row) }}</td><td class="whitespace-nowrap px-5 py-4 font-mono text-xs">{{ formatPrice(row.inputPrice) }}</td><td class="whitespace-nowrap px-5 py-4 font-mono text-xs">{{ formatPrice(row.outputPrice) }}</td><td class="whitespace-nowrap px-5 py-4 font-mono text-xs">{{ formatPrice(row.cacheReadPrice) }}</td><td class="whitespace-nowrap px-5 py-4">{{ row.groupCount }}</td></tr></tbody></table></div>
          <div class="flex flex-col gap-3 border-t border-white/10 px-5 py-4 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>{{ t('home.public.pricing.footerNote') }}</span><a v-if="props.detailsHref" :href="props.detailsHref" class="inline-flex items-center gap-1.5 font-semibold text-cyan-200">{{ t('home.public.pricing.browseModelPlaza') }} <Icon name="arrowRight" size="xs" aria-hidden="true" /></a></div>
        </template>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { computed, ref, toValue, type MaybeRefOrGetter } from 'vue'
import { useI18n } from 'vue-i18n'
import Icon from '@/components/icons/Icon.vue'
type PublicHomeDataStatus = 'idle' | 'loading' | 'ready' | 'unavailable' | 'error'
interface PublicHomePricingRow { platform: string; model: string; inputPrice: number | string | null; outputPrice: number | string | null; cacheReadPrice: number | string | null; perRequestPrice?: number | string | null; billingMode?: string | null; groupCount: number; groupName?: string; pricingSource?: 'configured' | 'official' | 'unavailable' }
const props = defineProps<{ pricingRows?: MaybeRefOrGetter<PublicHomePricingRow[]>; rows?: MaybeRefOrGetter<PublicHomePricingRow[]>; status?: MaybeRefOrGetter<PublicHomeDataStatus>; errorMessage?: string; retryable?: boolean; detailsHref?: string }>()
const emit = defineEmits<{ retry: [] }>()
const { t } = useI18n()
const searchQuery = ref('')
const platformFilter = ref('all')
const rows = computed(() => toValue(props.pricingRows ?? props.rows) || [])
const status = computed(() => toValue(props.status) || 'idle')
const platforms = computed(() => Array.from(new Set(rows.value.map((row) => row.platform))).sort((a, b) => a.localeCompare(b)))
const filteredRows = computed(() => { const query = searchQuery.value.trim().toLowerCase(); return rows.value.filter((row) => (platformFilter.value === 'all' || row.platform === platformFilter.value) && (!query || `${row.platform} ${row.model} ${row.groupName || ''}`.toLowerCase().includes(query))) })
function formatPrice(value: number | string | null | undefined): string { if (value === null || value === undefined || value === '') return '-'; const formatted = typeof value === 'number' ? value.toLocaleString(undefined, { maximumFractionDigits: 10, useGrouping: false }) : value; return `$${formatted}` }
function billingLabel(row: PublicHomePricingRow): string { if (row.billingMode === 'per_request') return row.perRequestPrice === null || row.perRequestPrice === undefined ? t('home.public.pricing.perRequest') : t('home.public.pricing.perRequestWithPrice', { price: formatPrice(row.perRequestPrice) }); if (row.billingMode === 'token') return t('home.public.pricing.tokenBilling'); if (row.billingMode) return row.billingMode.replace(/_/g, ' '); return row.pricingSource === 'official' ? t('home.public.pricing.reference') : t('home.public.pricing.notSpecified') }
function resetFilters(): void { searchQuery.value = ''; platformFilter.value = 'all' }
</script>
