package service

import (
	"context"
	"errors"

	infraerrors "github.com/Wei-Shaw/sub2api/internal/pkg/errors"
)

var (
	ErrBalancePrechargeInvalid  = errors.New("invalid balance precharge parameters")
	ErrBalancePrechargeNotFound = errors.New("balance precharge not found")
	ErrBalancePrechargeConflict = errors.New("balance precharge ownership or state conflict")
	// Waiting means existing holds could still fund this admission after settlement.
	// The repository has released its transaction before returning this error.
	ErrBalancePrechargeWaiting     = errors.New("balance temporarily reserved by other requests")
	ErrBalancePrechargeWaitTimeout = infraerrors.TooManyRequests("BALANCE_PRECHARGE_WAIT_TIMEOUT", "Timed out waiting for reserved balance to settle. Please retry later.")
)

// BalancePrechargeCommand snapshots one request's cash admission policy. ID must
// be generated by the server, independently of the client's usage dedup key.
type BalancePrechargeCommand struct {
	ID        string
	UserID    int64
	APIKeyID  int64
	GroupID   int64
	Threshold float64
	Amount    float64
	// MinimumBalance is checked against available funds before taking this hold.
	MinimumBalance float64
	LeaseOwner     string // Random server-owned token; never supplied by clients.
}

type BalancePrechargeResult struct {
	Reserved   bool
	Amount     float64
	NewBalance float64
}

// BalancePrechargeRepository is separate from UsageBillingRepository so existing
// billing implementations that do not support precharge remain source compatible.
type BalancePrechargeRepository interface {
	ReserveBalancePrecharge(context.Context, *BalancePrechargeCommand) (*BalancePrechargeResult, error)
	ReleaseBalancePrecharge(context.Context, string, int64) (bool, error)
}

// Recovery creates review evidence only. Expired ownership never refunds money.
type BalancePrechargeRecoveryRepository interface {
	RenewBalancePrechargeLease(context.Context, string, string) (bool, error)
	EndBalancePrechargeLease(context.Context, string, string) error
	RecoverBalancePrecharges(context.Context, int) (int, error)
}
