import type { ModelPolicy, ModelRun, ModelTestConfig } from '@/api/admin/upstream-model-monitoring'
import type { ManagedKey, RemoteGroup } from '@/api/admin/upstream-governance'
export const modelConfig: ModelTestConfig = { managed_key_id: 17, platform: 'openai', model: 'gpt-fixture', api_mode: 'chat_completions', efforts: ['medium'], templates: ['candy', 'token_audit'], samples: 1, concurrency: 1, max_output_tokens: 4096, timeout_seconds: 180, first_content_timeout_seconds: 60, idle_timeout_seconds: 30, input_tokens: 1024, tokenizer: 'auto', token_tolerance_percent: 10 }
export const modelKey: ManagedKey = { id: 17, site_id: 1, remote_group_id: 'remote-1', platform: 'openai', remote_key_id: 'fixture-key', marker: 'fixture-marker', has_key: true, created_at: '2026-09-27T12:00:00Z', updated_at: '2026-09-27T12:00:00Z' }
export const modelGroup: RemoteGroup = { id: 'remote-1', name: 'Fixture group', platform: 'openai', rate_multiplier: 1, user_rate_multiplier: null, resolved_rate_multiplier: 1, peak_rate_enabled: false, models: ['gpt-fixture'], prices: [], source: 'fixture' }
export const modelPolicy: ModelPolicy = { id: 8, site_id: 1, name: 'Daily fixture', config: modelConfig, enabled: false, interval_minutes: 1440, daily_request_limit: 100, notify_enabled: false, recipients: [], failure_threshold: 3, take_over_legacy: false, version: 4 }
export function modelRun(overrides: Partial<ModelRun> = {}): ModelRun {
  return { id: 'run-medium', batch_id: 'batch-fixture', site_id: 1, policy_id: null, sequence: 1, request: { config: modelConfig, template: 'candy', effort: 'medium', sample: 1 }, status: 'succeeded', review: 'pending', review_note: '', created_at: '2026-09-27T12:00:00Z', started_at: '2026-09-27T12:00:01Z', finished_at: '2026-09-27T12:00:02Z', result: { success: true, error_code: '', http_status: 200, response_model: 'gpt-fixture', effort_support: 'unverified_parameter', finish_reason: 'stop', ttft_ms: null, duration_ms: 1000, usage: { input_tokens: null, output_tokens: null, cached_tokens: null, reasoning_tokens: null }, tokens: { tokenizer: 'unknown', source: 'unavailable', input_local: null, output_local: null, input_state: 'usage_missing', output_state: 'usage_missing', input_delta_percent: null, output_delta_percent: null, input_hash: 'input-sha256', output_hash: 'output-sha256', input_bytes: 40, output_bytes: 2, input_chars: 20, output_chars: 2, note: 'fixture evidence' }, candy_verdict: 'numeric_correct', candy_answer: 21, response_text: '21', input_text: 'fixture prompt', request_body: { model: 'gpt-fixture' }, raw_usage: null }, ...overrides }
}
