import { mount, flushPromises } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import ManagedKeysPanel from './ManagedKeysPanel.vue'
import api, { type ManagedKey } from '@/api/admin/upstream-governance'

vi.mock('@/api/admin/upstream-governance', () => ({ default: { keys: vi.fn(), createKeys: vi.fn(), revealKey: vi.fn(), auditKeys: vi.fn(), keyRepair: vi.fn(), prepareKeyRepair: vi.fn(), confirmKeyRepair: vi.fn(), abandonKeyRepair: vi.fn() } }))
vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (key: string) => key }) }))
const key: ManagedKey = { id: 9, site_id: 1, remote_group_id: 'r', platform: 'openai', remote_key_id: '55', marker: 'fixture', has_key: true, created_at: 'now', updated_at: 'now' }
const props = { siteId: 1, snapshotId: 3, groups: [{ id: 'r', name: 'Remote' }], selections: [{ remote_group_id: 'r', platform: 'openai' as const }] }

describe('managed group keys', () => {
  beforeEach(() => {
    vi.resetAllMocks()
    vi.mocked(api.keys).mockResolvedValue([])
    Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: vi.fn().mockResolvedValue(undefined) } })
  })
  it('retains successful batch keys when a later batch times out, stops, and never automatically retries creation', async () => {
    const groups = Array.from({ length: 23 }, (_, index) => ({ id: String(index + 1), name: 'Group ' + (index + 1) }))
    const selections = groups.map(group => ({ remote_group_id: group.id, platform: 'openai' as const }))
    vi.mocked(api.createKeys).mockResolvedValueOnce({ items: groups.slice(0, 10).map((group, index) => ({ remote_group_id: group.id, platform: 'openai', status: 'created' as const, managed_key: { ...key, id: index + 1, remote_group_id: group.id }, key: 'secret-' + (index + 1) })) }).mockRejectedValueOnce({ reason: 'timeout' })
    const wrapper = mount(ManagedKeysPanel, { props: { ...props, groups, selections } })
    await flushPromises()
    await wrapper.get('[data-test=create-keys]').trigger('click')
    await flushPromises()
    expect(api.createKeys).toHaveBeenCalledTimes(2)
    expect(api.createKeys).toHaveBeenNthCalledWith(1, 1, { snapshot_id: 3, selections: selections.slice(0, 10) })
    expect(api.createKeys).toHaveBeenNthCalledWith(2, 1, { snapshot_id: 3, selections: selections.slice(10, 20) })
    expect(wrapper.findAll('[data-test=key-secret]')).toHaveLength(10)
    expect(wrapper.text()).toContain('secret-1')
    expect(wrapper.text()).toContain('governance.timeout')
    expect(wrapper.text()).toContain('governance.keyInterrupted')
    expect(wrapper.text()).toContain('governance.keyNotAttempted')
    await wrapper.get('[data-test=copy-all-keys]').trigger('click')
    expect(navigator.clipboard.writeText).toHaveBeenCalledWith('secret-1\nsecret-2\nsecret-3\nsecret-4\nsecret-5\nsecret-6\nsecret-7\nsecret-8\nsecret-9\nsecret-10')
  })
  it('creates selected group keys without a local mapping and retains per-item partial failures', async () => {
    vi.mocked(api.createKeys).mockResolvedValue({ items: [
      { remote_group_id: 'r', platform: 'openai', status: 'created', managed_key: key, key: 'fixture-secret' },
      { remote_group_id: 's', platform: 'anthropic', status: 'failed', error: 'timeout' },
    ] })
    const wrapper = mount(ManagedKeysPanel, { props: { ...props, groups: [...props.groups, { id: 's', name: 'Second' }], selections: [...props.selections, { remote_group_id: 's', platform: 'anthropic' }] } })
    await flushPromises()
    await wrapper.get('[data-test=create-keys]').trigger('click')
    await flushPromises()
    expect(api.createKeys).toHaveBeenCalledWith(1, { snapshot_id: 3, selections: [{ remote_group_id: 'r', platform: 'openai' }, { remote_group_id: 's', platform: 'anthropic' }] })
    expect(wrapper.get('[data-test=key-secret]').text()).toContain('fixture-secret')
    expect(wrapper.text()).toContain('governance.keyCreated')
    expect(wrapper.text()).toContain('governance.timeout')
    expect(wrapper.find('[data-test=reveal-key]').exists()).toBe(false)
    await wrapper.get('[data-test=copy-all-keys]').trigger('click')
    expect(navigator.clipboard.writeText).toHaveBeenCalledWith('fixture-secret')
  })
  it('automatically displays full saved keys and clears them when the site changes', async () => {
    vi.mocked(api.keys).mockResolvedValueOnce([key]).mockResolvedValue([])
    vi.mocked(api.revealKey).mockResolvedValue({ managed_key: key, key: 'revealed-secret' })
    const wrapper = mount(ManagedKeysPanel, { props })
    await flushPromises()
    expect(api.revealKey).toHaveBeenCalledWith(1, 9)
    expect(wrapper.get('[data-test=key-secret]').text()).toBe('revealed-secret')
    expect(wrapper.find('[data-test=reveal-key]').exists()).toBe(false)
    await wrapper.get('[data-test=copy-all-keys]').trigger('click')
    expect(navigator.clipboard.writeText).toHaveBeenCalledWith('revealed-secret')
    await wrapper.setProps({ siteId: 2 })
    expect(wrapper.text()).not.toContain('revealed-secret')
    expect(wrapper.find('[data-test=copy-all-keys]').exists()).toBe(false)
  })
  it('does not reveal a reserved key whose upstream creation is incomplete', async () => {
    vi.mocked(api.keys).mockResolvedValue([{ ...key, has_key: false }])
    const wrapper = mount(ManagedKeysPanel, { props })
    await flushPromises()
    expect(wrapper.find('[data-test=reveal-key]').exists()).toBe(false)
    expect(wrapper.text()).toContain('governance.keyPending')
    expect(api.revealKey).not.toHaveBeenCalled()
  })
  it('ignores a reveal response arriving after changing sites', async () => {
    vi.mocked(api.keys).mockResolvedValueOnce([key]).mockResolvedValue([])
    let resolve!: (value: { managed_key: ManagedKey; key: string }) => void
    vi.mocked(api.revealKey).mockImplementation(() => new Promise(r => { resolve = r }))
    const wrapper = mount(ManagedKeysPanel, { props })
    await flushPromises()
    expect(api.revealKey).toHaveBeenCalledTimes(1)
    await wrapper.setProps({ siteId: 2 })
    resolve({ managed_key: key, key: 'late-secret' })
    await flushPromises()
    expect(wrapper.text()).not.toContain('late-secret')
  })
  it('reads saved keys sequentially and displays each full value as it arrives', async () => {
    const second = { ...key, id: 10, remote_group_id: 's' }
    vi.mocked(api.keys).mockResolvedValue([key, second])
    let resolve!: (value: { managed_key: ManagedKey; key: string }) => void
    vi.mocked(api.revealKey).mockImplementationOnce(() => new Promise(r => { resolve = r })).mockResolvedValueOnce({ managed_key: second, key: 'second-full-key' })
    const wrapper = mount(ManagedKeysPanel, { props })
    await flushPromises()
    expect(api.revealKey).toHaveBeenCalledTimes(1)
    resolve({ managed_key: key, key: 'first-full-key' })
    await flushPromises()
    expect(api.revealKey).toHaveBeenNthCalledWith(2, 1, 10)
    expect(wrapper.findAll('[data-test=key-secret]').map(node => node.text())).toEqual(['first-full-key', 'second-full-key'])
    await wrapper.get('[data-test=copy-all-keys]').trigger('click')
    expect(navigator.clipboard.writeText).toHaveBeenCalledWith('first-full-key\nsecond-full-key')
  })
  it('retains loaded keys when another key fails to decrypt and offers a retry for that row', async () => {
    const second = { ...key, id: 10, remote_group_id: 's' }
    vi.mocked(api.keys).mockResolvedValue([key, second])
    vi.mocked(api.revealKey).mockResolvedValueOnce({ managed_key: key, key: 'first-full-key' }).mockRejectedValueOnce({ reason: 'operation_failed' }).mockResolvedValueOnce({ managed_key: second, key: 'recovered-full-key' })
    const wrapper = mount(ManagedKeysPanel, { props })
    await flushPromises()
    expect(wrapper.get('[data-test=key-secret]').text()).toBe('first-full-key')
    expect(wrapper.get('[data-test=key-read-error]').text()).toContain('governance.keyReadFailed')
    const retry = wrapper.get('#governance-reveal-key-10')
    expect(retry.text()).toBe('governance.rereadKey')
    await retry.trigger('click')
    await flushPromises()
    expect(wrapper.find('[data-test=key-read-error]').exists()).toBe(false)
    expect(wrapper.findAll('[data-test=key-secret]').map(node => node.text())).toEqual(['first-full-key', 'recovered-full-key'])
  })
  it('distinguishes a locally stored secret from a remotely missing key', async () => {
    vi.mocked(api.keys).mockResolvedValue([{ ...key, health: { status: 'confirmed_missing', last_checked_at: '2026-09-30T08:01:02Z', last_verified_at: null, missing_count: 2 } }])
    vi.mocked(api.revealKey).mockResolvedValue({ managed_key: key, key: 'saved-but-deleted' })
    const wrapper = mount(ManagedKeysPanel, { props })
    await flushPromises()
    expect(wrapper.get('[data-test=key-local-state]').text()).toContain('governance.keySavedLocally')
    expect(wrapper.get('[data-test=key-remote-state]').text()).toContain('governance.keyHealth_confirmed_missing')
    expect(wrapper.get('[data-test=key-health-checked]').text()).toContain('2026-09-30 16:01:02')
    expect(wrapper.get('[data-test=key-secret]').text()).toBe('saved-but-deleted')
  })
  it('runs a read-only key audit on demand and refreshes remote status without creating a key', async () => {
    vi.mocked(api.keys).mockResolvedValue([{ ...key, health: { status: 'suspected_missing', last_checked_at: null, last_verified_at: null, missing_count: 1 } }])
    vi.mocked(api.revealKey).mockResolvedValue({ managed_key: key, key: 'saved-key' })
    vi.mocked(api.auditKeys).mockResolvedValue([{ ...key, health: { status: 'present', last_checked_at: '2026-09-30T08:01:02Z', last_verified_at: '2026-09-30T08:01:02Z', missing_count: 0 } }])
    const wrapper = mount(ManagedKeysPanel, { props })
    await flushPromises()
    await wrapper.get('[data-test=audit-keys]').trigger('click')
    await flushPromises()
    expect(api.auditKeys).toHaveBeenCalledWith(1)
    expect(api.createKeys).not.toHaveBeenCalled()
    expect(wrapper.get('[data-test=key-remote-state]').text()).toContain('governance.keyHealth_present')
    expect(wrapper.get('[data-test=key-secret]').text()).toBe('saved-key')
  })
  it('shows a separate inventory error without claiming the key was deleted', async () => {
    vi.mocked(api.keys).mockResolvedValue([{ ...key, health: { status: 'present', last_checked_at: '2026-09-30T08:01:02Z', missing_count: 0, error_code: 'unsupported_contract' } }])
    vi.mocked(api.revealKey).mockResolvedValue({ managed_key: key, key: 'saved-key' })
    const wrapper = mount(ManagedKeysPanel, { props })
    await flushPromises()
    expect(wrapper.get('[data-test=key-remote-state]').text()).toContain('governance.keyHealth_present')
    expect(wrapper.get('[data-test=key-health-error]').text()).toContain('governance.keyAuditFailed')
    expect(wrapper.get('[data-test=key-health-error]').text()).toContain('governance.unsupported')
  })
  it('prepares a replacement without creating it, then advances only after explicit confirmation', async () => {
    const missing = { ...key, health: { status: 'confirmed_missing' as const, last_checked_at: '2026-09-30T08:01:02Z', missing_count: 2 } }
    vi.mocked(api.keys).mockResolvedValueOnce([missing]).mockResolvedValueOnce([{ ...key, remote_key_id: '77', health: { status: 'present', missing_count: 0 } }])
    vi.mocked(api.revealKey).mockResolvedValue({ managed_key: key, key: 'fixture-secret' })
    vi.mocked(api.keyRepair).mockResolvedValue(null)
    vi.mocked(api.prepareKeyRepair).mockResolvedValue({ id: 'repair-1', managed_key_id: 9, site_id: 1, remote_group_id: 'r', platform: 'openai', account_id: 5, account_name: 'Local GPT Lite', old_remote_key_id: '55', stage: 'prepared', error_code: '', created_at: '', updated_at: '' })
    vi.mocked(api.confirmKeyRepair).mockResolvedValue({ id: 'repair-1', managed_key_id: 9, site_id: 1, remote_group_id: 'r', platform: 'openai', account_id: 5, account_name: 'Local GPT Lite', old_remote_key_id: '55', candidate_remote_key_id: '77', stage: 'committed', error_code: '', created_at: '', updated_at: '' })
    const wrapper = mount(ManagedKeysPanel, { props: { ...props, siteVersion: 3 }, global: { stubs: { BaseDialog: { props: ['show'], template: '<div v-if="show"><slot /></div>' } } } })
    await flushPromises()
    await wrapper.get('[data-test=repair-key]').trigger('click')
    await flushPromises()
    expect(api.keyRepair).toHaveBeenCalledWith(1, 9)
    expect(api.prepareKeyRepair).not.toHaveBeenCalled()
    expect(api.confirmKeyRepair).not.toHaveBeenCalled()
    await wrapper.get('[data-test=prepare-key-repair]').trigger('click')
    await flushPromises()
    expect(api.prepareKeyRepair).toHaveBeenCalledWith(1, 9, { site_version: 3 })
    expect(api.confirmKeyRepair).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('Local GPT Lite')
    await wrapper.get('[data-test=confirm-key-repair]').trigger('click')
    await flushPromises()
    expect(api.confirmKeyRepair).toHaveBeenCalledTimes(1)
    expect(api.confirmKeyRepair).toHaveBeenCalledWith(1, 9, 'repair-1')
    expect(wrapper.text()).toContain('governance.keyRepairStage_committed')
  })
  it('clearly reviews and confirms a key-only replacement after the local account was deleted', async () => {
    vi.mocked(api.keys).mockResolvedValue([{ ...key, health: { status: 'confirmed_missing', missing_count: 2 } }])
    vi.mocked(api.revealKey).mockResolvedValue({ managed_key: key, key: 'fixture-secret' })
    const plan = { id: 'key-only', managed_key_id: 9, site_id: 1, remote_group_id: 'r', platform: 'openai' as const, mode: 'key_only' as const, account_id: 0, account_name: '', old_remote_key_id: '55', stage: 'prepared' as const, created_at: '', updated_at: '' }
    vi.mocked(api.keyRepair).mockResolvedValue(plan)
    vi.mocked(api.confirmKeyRepair).mockResolvedValue({ ...plan, stage: 'committed', candidate_remote_key_id: '77' })
    const wrapper = mount(ManagedKeysPanel, { props: { ...props, siteVersion: 3 } })
    await flushPromises()
    await wrapper.get('[data-test=repair-key]').trigger('click')
    await flushPromises()
    expect(wrapper.get('[data-test=repair-key-only-hint]').text()).toBe('governance.keyOnlyRepairHint')
    expect(wrapper.get('[data-test=confirm-key-repair]').text()).toBe('governance.confirmKeyOnlyRepair')
    expect(wrapper.get('[data-test=repair-plan]').text()).not.toContain('#0')
    expect(api.confirmKeyRepair).not.toHaveBeenCalled()
    await wrapper.get('[data-test=confirm-key-repair]').trigger('click')
    await flushPromises()
    expect(api.confirmKeyRepair).toHaveBeenCalledWith(1, 9, 'key-only')
    expect(wrapper.get('[data-test=repair-stage]').text()).toContain('governance.keyOnlyRepairStage_committed')
    expect(wrapper.emitted('repaired')).toHaveLength(1)
  })
  it('explains a repair conflict without asking for an unrelated import preview', async () => {
    vi.mocked(api.keys).mockResolvedValue([{ ...key, health: { status: 'confirmed_missing', missing_count: 2 } }])
    vi.mocked(api.revealKey).mockResolvedValue({ managed_key: key, key: 'fixture-secret' })
    vi.mocked(api.keyRepair).mockResolvedValue(null)
    vi.mocked(api.prepareKeyRepair).mockRejectedValue({ status: 409, reason: 'stale_preview' })
    const wrapper = mount(ManagedKeysPanel, { props: { ...props, siteVersion: 3 } })
    await flushPromises()
    await wrapper.get('[data-test=repair-key]').trigger('click')
    await flushPromises()
    await wrapper.get('[data-test=prepare-key-repair]').trigger('click')
    await flushPromises()
    expect(wrapper.get('[role=alert]').text()).toBe('governance.keyRepairConflict')
    expect(api.keyRepair).toHaveBeenCalledTimes(2)
    expect(api.confirmKeyRepair).not.toHaveBeenCalled()
    expect(api.createKeys).not.toHaveBeenCalled()
  })
  it('notifies the parent of a committed rebind even if refreshing the key list fails', async () => {
    vi.mocked(api.keys).mockResolvedValueOnce([{ ...key, health: { status: 'confirmed_missing', missing_count: 2 } }]).mockRejectedValueOnce(new Error('refresh failed'))
    vi.mocked(api.revealKey).mockResolvedValue({ managed_key: key, key: 'fixture-secret' })
    vi.mocked(api.keyRepair).mockResolvedValue({ id: 'repair-1', managed_key_id: 9, site_id: 1, remote_group_id: 'r', platform: 'openai', account_id: 5, account_name: 'Local GPT Lite', old_remote_key_id: '55', stage: 'candidate_ready', created_at: '', updated_at: '' })
    vi.mocked(api.confirmKeyRepair).mockResolvedValue({ id: 'repair-1', managed_key_id: 9, site_id: 1, remote_group_id: 'r', platform: 'openai', account_id: 5, account_name: 'Local GPT Lite', old_remote_key_id: '55', candidate_remote_key_id: '77', stage: 'committed', created_at: '', updated_at: '' })
    const wrapper = mount(ManagedKeysPanel, { props: { ...props, siteVersion: 3 } })
    await flushPromises()
    await wrapper.get('[data-test=repair-key]').trigger('click')
    await flushPromises()
    await wrapper.get('[data-test=confirm-key-repair]').trigger('click')
    await flushPromises()
    expect(wrapper.emitted('repaired')).toHaveLength(1)
    expect(wrapper.get('[data-test=repair-stage]').text()).toContain('governance.keyRepairStage_committed')
    expect(wrapper.get('[role=alert]').text()).toContain('governance.error')
  })
  it('recovers a durable preparation after the prepare response is lost', async () => {
    vi.mocked(api.keys).mockResolvedValue([{ ...key, health: { status: 'confirmed_missing', missing_count: 2 } }])
    vi.mocked(api.revealKey).mockResolvedValue({ managed_key: key, key: 'fixture-secret' })
    vi.mocked(api.keyRepair).mockResolvedValueOnce(null).mockResolvedValueOnce({ id: 'persisted-repair', managed_key_id: 9, site_id: 1, remote_group_id: 'r', platform: 'openai', account_id: 5, account_name: 'Local GPT Lite', old_remote_key_id: '55', stage: 'prepared', created_at: '', updated_at: '' })
    vi.mocked(api.prepareKeyRepair).mockRejectedValue(new Error('response lost'))
    const wrapper = mount(ManagedKeysPanel, { props: { ...props, siteVersion: 3 } })
    await flushPromises()
    await wrapper.get('[data-test=repair-key]').trigger('click')
    await flushPromises()
    await wrapper.get('[data-test=prepare-key-repair]').trigger('click')
    await flushPromises()
    expect(api.keyRepair).toHaveBeenCalledTimes(2)
    expect(api.prepareKeyRepair).toHaveBeenCalledTimes(1)
    expect(wrapper.get('[data-test=repair-stage]').text()).toContain('governance.keyRepairStage_prepared')
    expect(wrapper.find('[data-test=prepare-key-repair]').exists()).toBe(false)
    expect(wrapper.get('[data-test=confirm-key-repair]').exists()).toBe(true)
  })
  it('keeps an uncertain replacement for an explicit read-only retry', async () => {
    const missing = { ...key, health: { status: 'confirmed_missing' as const, missing_count: 2 } }
    vi.mocked(api.keys).mockResolvedValue([missing])
    vi.mocked(api.revealKey).mockResolvedValue({ managed_key: key, key: 'fixture-secret' })
    vi.mocked(api.keyRepair).mockResolvedValue({ id: 'repair-2', managed_key_id: 9, site_id: 1, remote_group_id: 'r', platform: 'openai', account_id: 5, account_name: 'Local GPT Lite', old_remote_key_id: '55', stage: 'awaiting_visibility', error_code: 'upstream_key_unverifiable', created_at: '', updated_at: '' })
    vi.mocked(api.confirmKeyRepair).mockResolvedValue({ id: 'repair-2', managed_key_id: 9, site_id: 1, remote_group_id: 'r', platform: 'openai', account_id: 5, account_name: 'Local GPT Lite', old_remote_key_id: '55', stage: 'awaiting_visibility', error_code: 'upstream_key_unverifiable', created_at: '', updated_at: '' })
    const wrapper = mount(ManagedKeysPanel, { props: { ...props, siteVersion: 3 }, global: { stubs: { BaseDialog: { props: ['show'], template: '<div v-if="show"><slot /></div>' } } } })
    await flushPromises()
    await wrapper.get('[data-test=repair-key]').trigger('click')
    await flushPromises()
    expect(api.confirmKeyRepair).not.toHaveBeenCalled()
    await wrapper.get('[data-test=confirm-key-repair]').trigger('click')
    await flushPromises()
    expect(api.confirmKeyRepair).toHaveBeenCalledTimes(1)
    expect(wrapper.text()).toContain('governance.keyRepairStage_awaiting_visibility')
  })
  it('requires an explicit acknowledgement before abandoning an uncertain creation result', async () => {
    vi.mocked(api.keys).mockResolvedValue([{ ...key, health: { status: 'confirmed_missing', missing_count: 2 } }])
    vi.mocked(api.revealKey).mockResolvedValue({ managed_key: key, key: 'fixture-secret' })
    vi.mocked(api.keyRepair).mockResolvedValue({ id: 'uncertain-repair', managed_key_id: 9, site_id: 1, remote_group_id: 'r', platform: 'openai', account_id: 5, account_name: 'Local GPT Lite', old_remote_key_id: '55', planned_key_name: 'GPT Lite-20260930-r12345678', stage: 'awaiting_visibility', can_abandon: true, created_at: '', updated_at: '' })
    vi.mocked(api.abandonKeyRepair).mockResolvedValue({ id: 'uncertain-repair', managed_key_id: 9, site_id: 1, remote_group_id: 'r', platform: 'openai', account_id: 5, account_name: 'Local GPT Lite', old_remote_key_id: '55', stage: 'abandoned', can_reprepare: true, created_at: '', updated_at: '' })
    const wrapper = mount(ManagedKeysPanel, { props: { ...props, siteVersion: 3 } })
    await flushPromises()
    await wrapper.get('[data-test=repair-key]').trigger('click')
    await flushPromises()
    expect(wrapper.get('[data-test=planned-key-name]').text()).toBe('GPT Lite-20260930-r12345678')
    expect(wrapper.get('[data-test=abandon-key-repair]').attributes('disabled')).toBeDefined()
    expect(api.abandonKeyRepair).not.toHaveBeenCalled()
    await wrapper.get('[data-test=acknowledge-key-repair]').setValue(true)
    await wrapper.get('[data-test=abandon-key-repair]').trigger('click')
    await flushPromises()
    expect(api.abandonKeyRepair).toHaveBeenCalledWith(1, 9, 'uncertain-repair', { acknowledge_uncertain_create: true })
    expect(api.confirmKeyRepair).not.toHaveBeenCalled()
    expect(api.prepareKeyRepair).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('governance.keyRepairStage_abandoned')
    expect(wrapper.find('[data-test=prepare-key-repair]').exists()).toBe(true)
  })
  it('offers a fresh preparation only for a conflict before remote creation intent', async () => {
    vi.mocked(api.keys).mockResolvedValue([{ ...key, health: { status: 'confirmed_missing', missing_count: 2 } }])
    vi.mocked(api.revealKey).mockResolvedValue({ managed_key: key, key: 'fixture-secret' })
    vi.mocked(api.keyRepair).mockResolvedValue({ id: 'old-repair', managed_key_id: 9, site_id: 1, remote_group_id: 'r', platform: 'openai', account_id: 5, account_name: 'Local GPT Lite', old_remote_key_id: '55', stage: 'conflict', can_reprepare: true, created_at: '', updated_at: '' })
    vi.mocked(api.prepareKeyRepair).mockResolvedValue({ id: 'new-repair', managed_key_id: 9, site_id: 1, remote_group_id: 'r', platform: 'openai', account_id: 5, account_name: 'Local GPT Lite', old_remote_key_id: '55', stage: 'prepared', created_at: '', updated_at: '' })
    const wrapper = mount(ManagedKeysPanel, { props: { ...props, siteVersion: 3 } })
    await flushPromises()
    await wrapper.get('[data-test=repair-key]').trigger('click')
    await flushPromises()
    expect(wrapper.find('[data-test=confirm-key-repair]').exists()).toBe(false)
    await wrapper.get('[data-test=prepare-key-repair]').trigger('click')
    await flushPromises()
    expect(api.prepareKeyRepair).toHaveBeenCalledWith(1, 9, { site_version: 3 })
    expect(api.confirmKeyRepair).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('governance.keyRepairStage_prepared')
  })
  it('can prepare a new repair when a previously replaced key goes missing again', async () => {
    vi.mocked(api.keys).mockResolvedValue([{ ...key, remote_key_id: '77', health: { status: 'confirmed_missing', missing_count: 2 } }])
    vi.mocked(api.revealKey).mockResolvedValue({ managed_key: { ...key, remote_key_id: '77' }, key: 'replacement-secret' })
    vi.mocked(api.keyRepair).mockResolvedValue({ id: 'completed-repair', managed_key_id: 9, site_id: 1, remote_group_id: 'r', platform: 'openai', account_id: 5, account_name: 'Local GPT Lite', old_remote_key_id: '55', candidate_remote_key_id: '77', stage: 'committed', created_at: '', updated_at: '' })
    vi.mocked(api.prepareKeyRepair).mockResolvedValue({ id: 'next-repair', managed_key_id: 9, site_id: 1, remote_group_id: 'r', platform: 'openai', account_id: 5, account_name: 'Local GPT Lite', old_remote_key_id: '77', stage: 'prepared', created_at: '', updated_at: '' })
    const wrapper = mount(ManagedKeysPanel, { props: { ...props, siteVersion: 4 } })
    await flushPromises()
    await wrapper.get('[data-test=repair-key]').trigger('click')
    await flushPromises()
    await wrapper.get('[data-test=prepare-key-repair]').trigger('click')
    await flushPromises()
    expect(api.prepareKeyRepair).toHaveBeenCalledWith(1, 9, { site_version: 4 })
    expect(wrapper.text()).toContain('governance.keyRepairStage_prepared')
  })
})
