import { enableAutoUnmount, flushPromises, mount } from '@vue/test-utils'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import ModelMonitorPanel from './ModelMonitorPanel.vue'
import Select from '@/components/common/Select.vue'
import api, { type ModelPolicy, type ModelRunPage } from '@/api/admin/upstream-model-monitoring'
import { modelConfig, modelGroup, modelKey, modelPolicy, modelRun } from './__tests__/model-fixtures'
vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (key: string) => key }) }))
vi.mock('@/api/admin/upstream-model-monitoring', () => ({ default: { policies: vi.fn(), runs: vi.fn(), stats: vi.fn(), startBatch: vi.fn(), savePolicy: vi.fn(), deletePolicy: vi.fn(), cancelBatch: vi.fn(), run: vi.fn(), review: vi.fn() } }))
enableAutoUnmount(afterEach)
const empty: ModelRunPage = { items: [], total: 0, page: 1, page_size: 20, counts: {} }
const setup = () => mount(ModelMonitorPanel, { props: { siteId: 1, remoteGroups: [modelGroup], managedKeys: [modelKey] } })
describe('model monitoring configuration and persistent work', () => {
  beforeEach(() => { vi.resetAllMocks(); vi.mocked(api.policies).mockResolvedValue([]); vi.mocked(api.runs).mockResolvedValue(empty); vi.mocked(api.stats).mockResolvedValue({ days: 7, groups: [] }) })
  afterEach(() => { vi.useRealTimers() })
  it('only reads on entry and submits explicit effort/template combinations with chosen concurrency', async () => {
    const wrapper = setup(); await flushPromises()
    expect(api.startBatch).not.toHaveBeenCalled(); expect(api.savePolicy).not.toHaveBeenCalled()
    await wrapper.get('[data-test=model-new]').trigger('click')
    expect(wrapper.get('[data-test=model-key]').text()).toContain('Fixture group')
    await wrapper.get('[data-test=model-effort-low]').setValue(true)
    await wrapper.get('[data-test=model-effort-high]').setValue(true)
    await wrapper.get('[data-test=model-samples]').setValue('2')
    await wrapper.get('[data-test=model-concurrency]').setValue('4')
    expect(wrapper.get('[data-test=model-request-count]').text()).toContain('12')
    vi.mocked(api.startBatch).mockResolvedValue({ id: 'batch-new', total: 12, concurrency: 4 })
    await wrapper.get('form').trigger('submit'); await flushPromises()
    const [id, input] = vi.mocked(api.startBatch).mock.calls[0]!
    expect(id).toBe(1); expect(input.request_id).toMatch(/^[\da-f]{8}-(?:[\da-f]{4}-){3}[\da-f]{12}$/)
    expect(input.config).toEqual({ ...modelConfig, efforts: ['medium', 'low', 'high'], samples: 2, concurrency: 4 })
    expect(api.savePolicy).not.toHaveBeenCalled()
  })
  it('saves a new policy paused with exact cadence and only enables it through an explicit action', async () => {
    const wrapper = setup(); await flushPromises(); await wrapper.get('[data-test=model-new]').trigger('click')
    await wrapper.get('[data-test=model-policy-interval]').setValue('1')
    await wrapper.get('[data-test=model-notify]').setValue(true)
    await wrapper.get('[data-test=model-recipients]').setValue('one@example.test, one@example.test\ntwo@example.test')
    vi.mocked(api.savePolicy).mockResolvedValue({ ...modelPolicy, interval_minutes: 1, version: 1 })
    vi.mocked(api.policies).mockResolvedValue([{ ...modelPolicy, interval_minutes: 1, version: 1 }])
    await wrapper.get('[data-test=model-policy-save]').trigger('click'); await flushPromises()
    expect(api.savePolicy).toHaveBeenCalledWith(1, expect.objectContaining({ id: 0, version: 0, enabled: false, interval_minutes: 1, notify_enabled: true, recipients: ['one@example.test', 'two@example.test'] }))
    await wrapper.get('[data-test=model-policy-toggle-8]').trigger('click'); await flushPromises()
    expect(vi.mocked(api.savePolicy).mock.calls[1]?.[1]).toMatchObject({ id: 8, version: 1, enabled: true })
    expect(api.startBatch).not.toHaveBeenCalled()
  })
  it('rejects fractional cadence, overlarge batches, and disabled submissions before queueing', async () => {
    const wrapper = setup(); await flushPromises(); await wrapper.get('[data-test=model-new]').trigger('click')
    await wrapper.get('[data-test=model-policy-interval]').setValue('1.5')
    await wrapper.get('[data-test=model-policy-save]').trigger('click')
    expect(api.savePolicy).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('governance.intervalPositiveInteger')
    await wrapper.get('[data-test=model-samples]').setValue('100')
    await wrapper.get('[data-test=model-effort-high]').setValue(true)
    await wrapper.get('form').trigger('submit')
    expect(api.startBatch).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('governance.modelMonitoring.invalidLimits')
    await wrapper.setProps({ disabled: true })
    await wrapper.get('form').trigger('submit')
    expect(api.startBatch).not.toHaveBeenCalled()
  })
  it('reuses the request id after an uncertain submission and creates another when configuration changes', async () => {
    const wrapper = setup(); await flushPromises(); await wrapper.get('[data-test=model-new]').trigger('click')
    vi.mocked(api.startBatch).mockRejectedValue({ status: 503 })
    await wrapper.get('form').trigger('submit'); await flushPromises()
    await wrapper.get('form').trigger('submit'); await flushPromises()
    expect(api.startBatch).toHaveBeenCalledTimes(2)
    const ids = vi.mocked(api.startBatch).mock.calls.map(call => call[1].request_id)
    expect(ids[1]).toBe(ids[0])
    await wrapper.get('[data-test=model-concurrency]').setValue('2')
    await wrapper.get('form').trigger('submit'); await flushPromises()
    expect(vi.mocked(api.startBatch).mock.calls[2]![1].request_id).not.toBe(ids[0])
  })
  it('validates phase timeouts against the overall deadline and scheduled rounds against their budget', async () => {
    const wrapper = setup(); await flushPromises(); await wrapper.get('[data-test=model-new]').trigger('click')
    await wrapper.get('[data-test=model-timeout]').setValue('10')
    await wrapper.get('form').trigger('submit')
    expect(api.startBatch).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('governance.modelMonitoring.timeoutOrderInvalid')
    await wrapper.get('[data-test=model-first-timeout]').setValue('5')
    await wrapper.get('[data-test=model-idle-timeout]').setValue('5')
    await wrapper.get('[data-test=model-daily-limit]').setValue('1')
    await wrapper.get('[data-test=model-policy-save]').trigger('click')
    expect(api.savePolicy).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('governance.modelMonitoring.dailyBudgetTooSmall')
  })
  it('can pause a broken existing policy when its managed key is no longer available', async () => {
    const active = { ...modelPolicy, enabled: true }
    vi.mocked(api.policies).mockResolvedValue([active])
    vi.mocked(api.savePolicy).mockResolvedValue({ ...active, enabled: false, version: 5 })
    const wrapper = setup(); await flushPromises(); await wrapper.setProps({ managedKeys: [] })
    await wrapper.get('[data-test=model-policy-toggle-8]').trigger('click'); await flushPromises()
    expect(api.savePolicy).toHaveBeenCalledWith(1, { ...active, enabled: false })
    expect(api.startBatch).not.toHaveBeenCalled()
  })
  it('opens the latest policy after an enable conflict and sends takeover only with explicit save-and-enable', async () => {
    vi.mocked(api.policies).mockResolvedValue([modelPolicy])
    const wrapper = setup(); await flushPromises()
    vi.mocked(api.savePolicy).mockRejectedValueOnce({ status: 409, reason: 'stale_preview' })
    const latest = { ...modelPolicy, version: 7 }
    vi.mocked(api.policies).mockResolvedValue([latest])
    await wrapper.get('[data-test=model-policy-toggle-8]').trigger('click'); await flushPromises()
    expect(api.savePolicy).toHaveBeenCalledWith(1, { ...modelPolicy, enabled: true, take_over_legacy: false })
    expect(wrapper.get('[data-test=model-editor]').exists()).toBe(true)
    expect(wrapper.text()).toContain('governance.modelMonitoring.enableConflictHint')
    expect((wrapper.get('[data-test=model-take-over]').element as HTMLInputElement).checked).toBe(false)
    await wrapper.get('[data-test=model-take-over]').setValue(true)
    const enabled = { ...latest, enabled: true, version: 8 }
    vi.mocked(api.savePolicy).mockResolvedValue(enabled)
    vi.mocked(api.policies).mockResolvedValue([enabled])
    await wrapper.get('[data-test=model-policy-save-enable]').trigger('click'); await flushPromises()
    expect(vi.mocked(api.savePolicy).mock.calls[1]?.[1]).toMatchObject({ id: 8, version: 7, enabled: true, take_over_legacy: true })
    expect((wrapper.get('[data-test=model-take-over]').element as HTMLInputElement).checked).toBe(false)
    expect(wrapper.find('[data-test=model-policy-save-enable]').exists()).toBe(false)
    expect(api.startBatch).not.toHaveBeenCalled()
  })
  it('does not retain takeover authorization after an ordinary paused-policy save', async () => {
    vi.mocked(api.policies).mockResolvedValue([modelPolicy])
    const wrapper = setup(); await flushPromises()
    await wrapper.get('[data-test=model-policy-edit-8]').trigger('click')
    await wrapper.get('[data-test=model-take-over]').setValue(true)
    const saved = { ...modelPolicy, version: 5 }
    vi.mocked(api.savePolicy).mockResolvedValue(saved); vi.mocked(api.policies).mockResolvedValue([saved])
    await wrapper.get('[data-test=model-policy-save]').trigger('click'); await flushPromises()
    expect(vi.mocked(api.savePolicy).mock.calls[0]?.[1]).toMatchObject({ enabled: false, take_over_legacy: true })
    expect((wrapper.get('[data-test=model-take-over]').element as HTMLInputElement).checked).toBe(false)
    await wrapper.get('[data-test=model-policy-toggle-8]').trigger('click'); await flushPromises()
    expect(vi.mocked(api.savePolicy).mock.calls[1]?.[1]).toMatchObject({ enabled: true, take_over_legacy: false, version: 5 })
  })
  it('ignores an old site response after switching sites', async () => {
    let finish!: (value: ModelRunPage) => void
    vi.mocked(api.runs).mockReturnValueOnce(new Promise(resolve => { finish = resolve }))
    const wrapper = setup(); await wrapper.setProps({ siteId: 2, managedKeys: [], remoteGroups: [] }); await flushPromises()
    finish({ ...empty, items: [modelRun()], total: 1 }); await flushPromises()
    expect(wrapper.find('[data-test=model-run-run-medium]').exists()).toBe(false)
    expect(api.runs).toHaveBeenLastCalledWith(2, 1, '')
  })
  it('uses whole-batch status counts, polls active work and stops polling after completion', async () => {
    vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout'] })
    vi.mocked(api.runs).mockResolvedValue({ ...empty, items: [modelRun({ status: 'running' })], total: 60, counts: { succeeded: 49, queued: 10, running: 1 } })
    const wrapper = setup(); await flushPromises()
    await wrapper.findAll('button').find(button => button.text() === 'governance.modelMonitoring.viewBatch')!.trigger('click'); await flushPromises()
    expect(wrapper.get('[role=progressbar]').attributes('aria-valuenow')).toBe('82')
    vi.mocked(api.runs).mockResolvedValue({ ...empty, items: [modelRun()], total: 60, counts: { succeeded: 60 } })
    await vi.advanceTimersByTimeAsync(4000); await flushPromises()
    expect(wrapper.get('[role=progressbar]').attributes('aria-valuenow')).toBe('100')
    const calls = vi.mocked(api.runs).mock.calls.length
    await vi.advanceTimersByTimeAsync(8000); await flushPromises()
    expect(api.runs).toHaveBeenCalledTimes(calls)
    wrapper.unmount(); await vi.advanceTimersByTimeAsync(8000)
    expect(api.runs).toHaveBeenCalledTimes(calls)
  })
  it('cancels only the selected batch and sends optimistic policy revisions when deleting', async () => {
    vi.mocked(api.runs).mockResolvedValue({ ...empty, items: [modelRun({ status: 'queued' })], total: 1, counts: { queued: 1 } })
    vi.mocked(api.policies).mockResolvedValue([modelPolicy])
    const wrapper = setup(); await flushPromises()
    await wrapper.findAll('button').find(button => button.text() === 'governance.modelMonitoring.viewBatch')!.trigger('click'); await flushPromises()
    await wrapper.get('[data-test=model-batch-cancel]').trigger('click'); await flushPromises()
    expect(api.cancelBatch).toHaveBeenCalledWith(1, 'batch-fixture')
    await wrapper.get('button[aria-label="common.delete"]').trigger('click')
    await wrapper.get('[data-test=model-policy-delete-8]').trigger('click'); await flushPromises()
    expect(api.deletePolicy).toHaveBeenCalledWith(1, 8, 4)
  })
  it('keeps exact statistics groups separate and does not display unsupported small-sample percentiles', async () => {
    const group = { model: 'gpt-fixture', api_mode: 'responses' as const, managed_key_id: 17, template: 'candy' as const, effort: 'medium' as const, config_hash: 'first', samples: 3, successes: 3, failures: 0, unknown: 0, comparable: true, ttft_samples: 3, p50_ttft_ms: 123, p95_ttft_ms: 234, avg_duration_ms: 500, last_run_at: '2026-09-27T12:00:00Z', points: [] }
    vi.mocked(api.stats).mockResolvedValue({ days: 7, groups: [group, { ...group, effort: 'high', config_hash: 'second', samples: 8, ttft_samples: 8, p95_ttft_ms: 987 }] })
    const wrapper = setup(); await flushPromises()
    const section = wrapper.get('[data-test=model-stats]')
    expect(section.findAll('details')).toHaveLength(2)
    expect(section.text()).toContain('governance.modelMonitoring.insufficientSamples')
    expect(section.text()).toContain('987'); expect(section.text()).not.toContain('234')
    wrapper.findAllComponents(Select).find(select => select.attributes('data-test') === 'model-stats-window')!.vm.$emit('update:modelValue', 30)
    await flushPromises(); expect(api.stats).toHaveBeenLastCalledWith(1, 30)
  })
  it('keeps a later policy response from applying to a new site', async () => {
    let finish!: (value: ModelPolicy) => void
    vi.mocked(api.savePolicy).mockReturnValue(new Promise(resolve => { finish = resolve }))
    const wrapper = setup(); await flushPromises(); await wrapper.get('[data-test=model-new]').trigger('click')
    await wrapper.get('[data-test=model-policy-save]').trigger('click')
    await wrapper.setProps({ siteId: 2, managedKeys: [], remoteGroups: [] }); await flushPromises()
    finish(modelPolicy); await flushPromises()
    expect(wrapper.find('[data-test=model-editor]').exists()).toBe(false)
    expect(wrapper.text()).not.toContain('Daily fixture')
  })
})
