import { mount, flushPromises } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import OnboardDialog from './OnboardDialog.vue'
import api, { type Site, type Snapshot } from '@/api/admin/upstream-governance'
import Select from '@/components/common/Select.vue'

vi.mock('@/api/admin/upstream-governance', () => ({ default: { detect: vi.fn(), create: vi.fn(), connect: vi.fn(), sync: vi.fn(), authStatus: vi.fn(), loginCredentials: vi.fn() } }))
vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (key: string) => key }) }))
const site: Site = { id: 8, name: 'Detected', platform: 'sub2api', base_url: 'https://fixture.example', proxy_id: null, enabled: true, interval_minutes: 15, version: 1, has_credential: false, status: 'disconnected', last_error: '', last_sync_at: null }
const snapshot: Snapshot = { id: 10, site_id: 8, site_version: 2, created_at: 'now', catalog: { groups: [], channels: [], warnings: [] } }
function mountDialog() {
  return mount(OnboardDialog, { props: { proxies: [] }, global: { stubs: {
    BaseDialog: { template: '<div><slot /></div>' },
    BrowserAuthorizationDialog: { template: '<button data-test="complete-browser" @click="$emit(\'connected\')">Complete</button>' },
  } } })
}
async function fill(wrapper: ReturnType<typeof mountDialog>) {
  await wrapper.get('#governance-onboard-url').setValue(site.base_url)
  await wrapper.get('#governance-onboard-username').setValue('fixture-user')
  await wrapper.get('#governance-onboard-password').setValue('fixture-password')
}
async function submit(wrapper: ReturnType<typeof mountDialog>) {
  await wrapper.get('form').trigger('submit')
  await flushPromises()
}
async function choose(selector: string, label: string, wrapper: ReturnType<typeof mountDialog>) {
  await wrapper.get(selector).trigger('click')
  const option = [...document.querySelectorAll<HTMLElement>('.select-dropdown-portal [role="option"]')].find(item => item.textContent?.includes(label))
  expect(option).toBeDefined()
  option!.click()
  await flushPromises()
}

describe('native onboarding continuation', () => {
  beforeEach(() => {
    vi.resetAllMocks()
    vi.mocked(api.detect).mockResolvedValue({ platform: 'sub2api', base_url: site.base_url, name: 'Detected', captcha_required: false })
    vi.mocked(api.create).mockResolvedValue(site)
    vi.mocked(api.connect).mockResolvedValue({ site: { ...site, has_credential: true } })
    vi.mocked(api.sync).mockResolvedValue(snapshot)
  })
  it('reloads authorization after a successful login advances the site version but collection requires reauthorization', async () => {
    const updated={...site,version:2,has_credential:true,status:'connected'}
    vi.mocked(api.connect).mockResolvedValue({site:updated})
    vi.mocked(api.sync).mockRejectedValue({reason:'reauth_required'})
    vi.mocked(api.authStatus).mockImplementation(async()=>({session:{site_id:8,site_version:vi.mocked(api.authStatus).mock.calls.length===1?1:2} as Awaited<ReturnType<typeof api.authStatus>>['session'],browser:{available:true,reason:''}}))
    vi.mocked(api.loginCredentials).mockResolvedValue({username:'fixture-user',password:'fixture-password',version:2})
    const wrapper=mountDialog()
    await fill(wrapper)
    await submit(wrapper)
    expect(vi.mocked(api.authStatus).mock.calls.length).toBeGreaterThanOrEqual(2)
    expect(wrapper.get('#governance-onboard-browser').attributes('disabled')).toBeUndefined()
    expect((wrapper.get('#governance-onboard-password').element as HTMLInputElement).value).toBe('fixture-password')
  })
  it('retains the created site when authentication fails and retries the same site', async () => {
    vi.mocked(api.connect).mockRejectedValueOnce({ reason: 'reauth_required' })
    const wrapper = mountDialog()
    await fill(wrapper)
    await submit(wrapper)
    expect(wrapper.emitted('completed')).toBeUndefined()
    expect(wrapper.text()).toContain('governance.siteSaved')
    expect(api.sync).not.toHaveBeenCalled()
    await wrapper.get('#governance-onboard-password').setValue('correct-password')
    await submit(wrapper)
    expect(api.create).toHaveBeenCalledTimes(1)
    expect(api.detect).toHaveBeenCalledTimes(1)
    expect(api.connect).toHaveBeenLastCalledWith(8, expect.objectContaining({ password: 'correct-password' }))
    expect(wrapper.emitted('completed')?.[0]).toEqual([{ ...site, has_credential: true }, snapshot])
  })
  it('offers browser authorization for an unsupported provider and collects only after explicit completion', async () => {
    vi.mocked(api.connect).mockResolvedValueOnce({ challenge: { kind: 'captcha', provider: 'aliyun' } })
    vi.mocked(api.authStatus).mockResolvedValue({ session: { site_id: 8, site_version: 1 } as Awaited<ReturnType<typeof api.authStatus>>['session'], browser: { available: true, reason: '' } })
    const wrapper = mountDialog()
    await fill(wrapper)
    await submit(wrapper)
    expect(wrapper.text()).toContain('governance.captchaProvider_aliyun')
    expect(wrapper.find('#governance-onboard-captcha').exists()).toBe(false)
    expect(wrapper.get('#governance-onboard-submit').attributes('disabled')).toBeDefined()
    await wrapper.get('#governance-onboard-browser').trigger('click')
    expect(api.sync).not.toHaveBeenCalled()
    await wrapper.get('[data-test=complete-browser]').trigger('click')
    await flushPromises()
    expect(api.sync).toHaveBeenCalledWith(8)
    expect(api.connect).toHaveBeenCalledTimes(1)
    expect(wrapper.emitted('completed')).toHaveLength(1)
  })
  it('retries a failed collection without asking for another password or creating another site', async () => {
    vi.mocked(api.sync).mockRejectedValueOnce({ reason: 'timeout' }).mockResolvedValueOnce(snapshot)
    const wrapper = mountDialog()
    await fill(wrapper)
    await submit(wrapper)
    expect(wrapper.emitted('completed')).toBeUndefined()
    expect(wrapper.find('#governance-onboard-password').exists()).toBe(false)
    expect(wrapper.emitted('created')?.at(-1)?.[0]).toMatchObject({ id: 8, has_credential: true })
    expect(wrapper.get('#governance-onboard-submit').text()).toBe('governance.retryCollection')
    await submit(wrapper)
    expect(api.create).toHaveBeenCalledTimes(1)
    expect(api.connect).toHaveBeenCalledTimes(1)
    expect(api.sync).toHaveBeenCalledTimes(2)
    expect(wrapper.emitted('completed')).toHaveLength(1)
  })
  it('keeps CAPTCHA incomplete and preserves transient password for the challenge continuation', async () => {
    vi.mocked(api.connect).mockResolvedValueOnce({ challenge: { kind: 'captcha' } }).mockResolvedValueOnce({ site: { ...site, has_credential: true } })
    const wrapper = mountDialog()
    await fill(wrapper)
    await submit(wrapper)
    expect(wrapper.emitted('completed')).toBeUndefined()
    expect(api.sync).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('governance.interactive')
    expect((wrapper.get('#governance-onboard-password').element as HTMLInputElement).value).toBe('fixture-password')
    await wrapper.get('#governance-onboard-captcha').setValue('valid-proof')
    await submit(wrapper)
    expect(api.connect).toHaveBeenLastCalledWith(8, expect.objectContaining({ password: 'fixture-password', captcha_token: 'valid-proof' }))
    expect(api.create).toHaveBeenCalledTimes(1)
    expect(wrapper.emitted('completed')).toHaveLength(1)
    expect(wrapper.find('#governance-onboard-password').exists()).toBe(false)
  })
  it('continues an opaque TOTP challenge with no retained password', async () => {
    vi.mocked(api.connect).mockResolvedValueOnce({ challenge: { kind: 'totp', token: 'opaque-proof' } }).mockResolvedValueOnce({ site: { ...site, has_credential: true } })
    const wrapper = mountDialog()
    await fill(wrapper)
    await submit(wrapper)
    expect((wrapper.get('#governance-onboard-password').element as HTMLInputElement).value).toBe('')
    expect(wrapper.html()).not.toContain('opaque-proof')
    await wrapper.get('#governance-onboard-otp').setValue('123456')
    await submit(wrapper)
    expect(api.connect).toHaveBeenLastCalledWith(8, expect.objectContaining({ password: '', otp: '123456', challenge_token: 'opaque-proof' }))
    expect(api.sync).toHaveBeenCalledTimes(1)
  })
  it('does not offer CAPTCHA proof for an unsupported browser verification and requires advanced continuation', async () => {
    vi.mocked(api.connect).mockResolvedValueOnce({ challenge: { kind: 'interactive_verification' } })
    const wrapper = mountDialog()
    await fill(wrapper)
    await submit(wrapper)
    expect(wrapper.find('#governance-onboard-captcha').exists()).toBe(false)
    expect(wrapper.text()).toContain('governance.unsupportedChallenge')
    expect(wrapper.get('#governance-onboard-submit').attributes('disabled')).toBeDefined()
    await submit(wrapper)
    expect(api.connect).toHaveBeenCalledTimes(1)
    expect(api.sync).not.toHaveBeenCalled()
    await wrapper.get('#governance-onboard-advanced-auth').trigger('click')
    await choose('#governance-onboard-auth-mode', 'governance.sessionLogin', wrapper)
    await wrapper.get('#governance-onboard-session').setValue('fixture-session')
    await submit(wrapper)
    expect(api.connect).toHaveBeenLastCalledWith(8, { session_token: 'fixture-session', user_id: undefined, expected_site_version: 1 })
    expect(api.sync).toHaveBeenCalledTimes(1)
  })
  it('uses consistent portal dropdowns for the advanced site platform and proxy', async () => {
    const wrapper = mount(OnboardDialog, { props: { proxies: [{ id: 42, name: 'Fixture proxy' }] }, global: { stubs: { BaseDialog: { template: '<div><slot /></div>' } } } })
    await wrapper.get('#governance-onboard-advanced').trigger('click')
    expect(wrapper.findAllComponents(Select)).toHaveLength(2)
    expect(wrapper.findAll('select')).toHaveLength(0)
    await choose('#governance-onboard-platform', 'New API', wrapper)
    await choose('#governance-onboard-proxy', 'Fixture proxy', wrapper)
    await wrapper.get('#governance-onboard-url').setValue('https://fixture.example')
    await wrapper.get('#governance-onboard-username').setValue('fixture-user')
    await wrapper.get('#governance-onboard-password').setValue('fixture-password')
    await submit(wrapper)
    expect(api.create).toHaveBeenCalledWith(expect.objectContaining({ platform: 'newapi', proxy_id: 42 }))
    wrapper.unmount()
  })
  it('does not continue onboarding if navigation occurs while platform detection is pending', async () => {
    let resolve!: (value: Awaited<ReturnType<typeof api.detect>>) => void
    vi.mocked(api.detect).mockImplementation(() => new Promise(r => { resolve = r }))
    const wrapper = mountDialog()
    await fill(wrapper)
    await wrapper.get('form').trigger('submit')
    wrapper.unmount()
    resolve({ platform: 'sub2api', base_url: site.base_url, name: 'Detected', captcha_required: false })
    await flushPromises()
    expect(api.create).not.toHaveBeenCalled()
    expect(api.connect).not.toHaveBeenCalled()
  })
})
